{{- if and .Values.jmxExporter.coordinator.enabled .Values.jmxExporter.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "trino.coordinator" . }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
spec:
  jobLabel: {{ .Release.Name }}-coordinator
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "trino.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: coordinator
  endpoints:
    - port: {{ .Values.jmxExporter.serviceMonitor.port }}
      {{- with .Values.jmxExporter.serviceMonitor.path }}
      path: {{ . }}
      {{- end }}
      {{- with .Values.jmxExporter.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.jmxExporter.serviceMonitor.scrapeTimeout  }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .Values.jmxExporter.serviceMonitor.relabelings  }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
