apiVersion: v1
kind: Service
metadata:
  name: {{ template "trino.fullname" . }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
  {{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}  
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.server.config.http.port }}
      targetPort: http-coord
      protocol: TCP
      name: http-coord
  selector:
    {{- include "trino.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
