{{- if .Values.jmxExporter.coordinator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "trino.coordinator" . }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.jmxExporter.port | default 9000 }}
      targetPort: jmx-exporter
      protocol: TCP
      name: {{ .Values.jmxExporter.serviceMonitor.port | default "jmx-exporter" }}
  selector:
    {{- include "trino.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
{{- end }}